### ISSUE TITLE
Enhance fast integration test to not use Service Catalog components

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#13415]
**Description**

After migration from service catalog into btp-operator we need to improve our e2e fast-integration test. We need to test the new way of application connectivity.

**Reasons**

Service Catalog components are gone. We need to use another mechanism to make that test usable.

**AC**

- [x] 1) create new pipeline skr-aws-without-sc-integration-dev that works without service catalog components
- [x] 2) in test use application-connectivity with central gateway that is already available 
  - see: https://github.com/kyma-project/kyma/tree/main/components/central-application-gateway#compass-mode
- [x] 4) switch all pipelines that uses fast-integration to the one without service catalog components WHEN Kyma has no SC Components

**Link**
- current pipeline with central app-con: https://status.build.kyma-project.io/?job=post-main-kyma-integration-k3d-central-app-connectivity-compass
- current test with central app-con: https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/compass-test/compass-test.js

**Comment by wozniakjan** [comment]
> * [ ]  1) create new pipeline skr-aws-without-sc-integration-dev that works without service catalog components

there is  [`skr-aws-integration-dev`](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-integration-dev) test already, should it be used as a starting point for the new test?

>  * [ ] 2) in test use application-connectivity with central gateway that is already available

but I think the `skr-aws-integration-dev` doesn't use compass-mode? And after reading https://github.com/kyma-project/kyma/tree/main/components/central-application-gateway#compass-mode, I'm not much clearer on what it actually achieves

> * [ ] 4) switch all pipelines that uses fast-integration to the one without service catalog components WHEN Kyma has no SC Components

Does this mean we should make btp-operator credentials compulsory for each fast-integration test or is there easier path?
https://github.com/kyma-project/kyma/blob/2d850e10ca475d6125d035a459a94a53fd339eb1/tests/fast-integration/kyma-environment-broker/client.js#L91

**Comment by wozniakjan** [comment]
@tillknuesting for the new test `skr-aws-without-sc-integration-dev`, we should start with modifying this function for SKR provisioning
https://github.com/kyma-project/kyma/blob/2d850e10ca475d6125d035a459a94a53fd339eb1/tests/fast-integration/kyma-environment-broker/client.js#L91

it should support also getting only `btpOperatorCredentials`, with `platformCreds == null`
The request then has payload with context in following form
```
   "context":{
       ...
       "sm_operator_credentials": {
         "clientid": "testClientID",
         "clientsecret": "testClientSecret",
         "sm_url": "https://service-manager.kyma.com",
         "url": "https://test.auth.com",
         "xsappname": "testXsappname"
       }
   },
```

There is this code that generates BTP operator credentials that I think we may reuse here too until we migrate on the ERS side the region that runs these tests, what do you think @PK85 
https://github.com/kyma-project/kyma/blob/2d850e10ca475d6125d035a459a94a53fd339eb1/tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js#L57

**Comment by tillknuesting** [comment]
My suggestion for migration to new skr test  would be to change target in makefile to new folder after merge:

https://github.com/kyma-project/kyma/blob/58802dcb8f4c8229fc7f3f68d50e9fe2a9df6b09/tests/fast-integration/Makefile#L24

**Comment by tillknuesting** [comment]
Currently the pipleine fails cause of audit event check:

```
  2) Execute SKR test
       CommerceMockTest()
         Amount of audit events must not exceed a certain threshold:
     TypeError: Cannot read property 'value' of undefined
      at checkAuditEventsThreshold (audit-log/helpers.js:58:40)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test-without-sc/skr-test.js:163:9)
```
This happens because no value is returned by Prometheus https://github.com/kyma-project/kyma/blob/58802dcb8f4c8229fc7f3f68d50e9fe2a9df6b09/tests/fast-integration/audit-log/helpers.js#L57

**Comment by tillknuesting** [comment]
commerceMockTest() has to be reviewed again on which parts are not needed anymore

**Comment by PK85** [comment]
When tests will be finished and we will see green runs, then to adjust all pipelines it's worth to just change content of the skr-tests directory with content from skr-test-without-sc.

**Comment by wozniakjan** [comment]
> * [x]  1) create new pipeline skr-aws-without-sc-integration-dev that works without service catalog components

>  * [x] 2) in test use application-connectivity with central gateway that is already available

I think those are done in https://github.com/kyma-project/kyma/pull/13801, trying to get it reviewed

> * [ ] 4) switch all pipelines that uses fast-integration to the one without service catalog components WHEN Kyma has no SC Components

> When tests will be finished and we will see green runs, then to adjust all pipelines it's worth to just change content of the skr-tests directory with content from skr-test-without-sc.

this should be reasonably simple but I guess we should do this after the test environment is configured to do so.

```
$ cd tests/fast-integration/
$ mv skr-test-without-sc/* skr-test/
```

**Comment by tillknuesting** [comment]
In the sprint review, it was discussed to introduce the possibility to configure the btp operator credentials via environment variables - after the task from this ticket are completed.

**Comment by tillknuesting** [comment]
remove usage of oidc: this.options.oidc0, for provisioning and replace oidc0 with config when used in test for comparison:

**Comment by Sawthis** [comment]
Please enable pre-main-kyma-integration-k3d-central-app-connectivity-compass after this issue will be fixed.
PR for disable the job: https://github.com/kyma-project/test-infra/pull/5304

**Comment by tillknuesting** [comment]
> Please enable pre-main-kyma-integration-k3d-central-app-connectivity-compass after this issue will be fixed. PR for disable the job: [kyma-project/test-infra#5304](https://github.com/kyma-project/test-infra/pull/5304)

Fix provided here https://github.com/kyma-project/kyma/pull/14071/files

**Comment by PK85** [comment]
TODO:
1.1) - [ ] PR merge test skr_without sc
1.2) - [ ] PR merge test infra for without sc
2.1) - [ ] PR reflect changes into skt-test directory (Kyma repo)
2.2) - [ ] adjust skr-test prow job to get btp-operator creds injected
3.1) - [ ] clean up fast-integration test service catalog, helm-broker code which is not used in skr-test anymore

**Comment by tillknuesting** [comment]
PR reflect changes into skt-test directory (Kyma repo) https://github.com/kyma-project/kyma/pull/14117/files and adjust skr-test prow job to get btp-operator creds injected
 https://github.com/kyma-project/test-infra/pull/5359/files

**Comment by Sawthis** [comment]
@wozniakjan @PK85 @tillknuesting what is the status of this issue? It's release blocker for Kyma Runtime 2.3 release and should be fixed before 15th of June.

**Comment by tillknuesting** [comment]
> @wozniakjan @PK85 @tillknuesting what is the status of this issue? It's release blocker for Kyma Runtime 2.3 release and should be fixed before 15th of June.

The main goal of having fast-integration tests without service catalog has been in my view been achieved. The skr integration test e.g. skr-aws-integration-dev runs without sc. There is additional refactoring in progress e.g. removing code that is not used anymore - therefore not closed yet. I would suggest to move refactoring and cleaning up dead code to another ticket in case this blocks the release.

**Comment by tillknuesting** [comment]
related PRs to this task:

https://github.com/kyma-project/test-infra/pull/5405
https://github.com/kyma-project/kyma/pull/14399
https://github.com/kyma-project/kyma/pull/14409
https://github.com/kyma-project/kyma/pull/14410

**Comment by arturskorupa** [comment]
@tillknuesting is the test still failing ? I must see green test before OS RC release

**Comment by tillknuesting** [comment]
> @tillknuesting is the test still failing ? I must see green test before OS RC release

Green test has already been achieved quite some time ago. The current problems problems are not related to this task.

**Comment by wozniakjan** [comment]
shouldn't be relase blocker for 2.3, svcat is getting purged in 2.4

**Comment by PK85** [comment]
Done
