### ISSUE TITLE
Failing Pipeline: kyma-upgrade-gardener-kyma2-minor-versions - In-Cluster Event not sent

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#16059]
**Description**
The pipeline [kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions) is failing due to the following issue:

```
  1) Upgrade test tests
       in-cluster event should be delivered (legacy events, structured and binary cloud events):
     Error: Request failed with status code 503
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Expected result**

In-Cluster event should be sent.

**Comment by VladislavPaskar** [comment]
We can re-enable this pipeline after this [PR](https://github.com/kyma-project/kyma/pull/16278) gets released.

**Comment by jeremyharisch** [comment]
Pipeline was not reenabled until now, I will re-open the ticket

**Comment by ruanxin** [comment]
Hi @VladislavPaskar , can you take care this issue and bring back the pipeline? The PR you mentioned which blocking this has been merged 5 days ago.

**Comment by VladislavPaskar** [comment]
> Hi @VladislavPaskar , can you take care this issue and bring back the pipeline? The PR you mentioned which blocking this has been merged 5 days ago.

@ruanxin this pipeline is testing the upgrade from one version to the latest minor **released** version. The fix, which got merged 5 days ago is already on main, but wasn't released yet, so it could be caught up by the pipeline. So, as already mentioned, we need to wait, until the fix gets released and then we can re-enable the pipeline and make sure it got fixed.

**Comment by ruanxin** [comment]
@VladislavPaskar , thanks for the update. Can you tell a bit more in detail when can we expect it? tbh, I don't see the problem why we need to wait for the next version released, if we bring back this pipeline (it's a periodical one, not blocking PR or any downstream release process, or?), it will fail for the next a few run, but after the minor fixed released, it will eventually works, right? Since our team knows this problem, we can make sure only report further issue after next release but ignore the one before that.

**Comment by jeremyharisch** [comment]
@ruanxin @VladislavPaskar Yes, this pipeline tests from second latest released Kyma to latest release. Thus, if we bring it back now it will fail until next release, which is planed for 28th of December. Thus, it will fail for over two weeks and thus, be removed again by `neighbours`.

@Sawthis what do you think? Reintroduce them now, but it will fail until end of December. Or Tunas need to make sure to reintroduce it at same time as release is happening.

@VladislavPaskar one more question, since we currently have a breaking bug in eventing when a customer tries to upgrade its Kyma cluster. Don't you think we should release earlier, since every customer will encounter this situation when 2.9.2 goes live. @Sawthis you are managing the 2.9.x releases - Would also be good to get your opinion here.

(cc @zhoujing2022)

**Comment by Sawthis** [comment]
@jeremyharisch I don't know anything about breaking bug in the eventing. If you think it is worth to release it earlier you should request hot-fix patch release.

About pipeline, there is no value to reintroduce it now if it will fail for 2 weeks every day. Let's wait and reintroduce it when 2.9.3 will be released. 

CC: @zhoujing2022

**Comment by jeremyharisch** [comment]
@Sawthis but that is exactly what this pipeline  has been testing - Deploy Kyma 2.9.1 and then upgrade 2.9.2 (second latest to latest).

This pipeline was then failing because of a bug in eventing, issue was created and assigned to Tunas. Meanwhile, neighbours decided to delete the pipeline because it seemed for them nobody takes care. Tunas as well as Jellyfish did not approve this removal. Thus, the pipeline got lost since we did not get any alerts any more.

The bug got fixed by this PR: https://github.com/kyma-project/kyma/pull/16278
Thus, the fix is not on main and will be released with 2.9.3. 

What I want? @VladislavPaskar the Tunas should test the following scenarios to make sure it is indeed working as @Sawthis mentioned.

Please test:
- deploy 2.9.1 upgrade to 2.9.2
- deploy 2.9.2 upgrade to main

If those two scenarios are working, we are good. But at least what the pipeline tells us, is that the upgrade test for eventing was not working 
```
Upgrade test tests
       in-cluster event should be delivered (legacy events, structured and binary cloud events):
     Error: Request failed with status code 503
```

**Comment by Sawthis** [comment]
@jeremyharisch feel free to update code owners in the test-infra repository. I've asked for review all teams but I didn't receive any response about this pipeline.

Please test locally first if upgrade from 2.9.2 to 2.9.3 works then you can reintroduce the pipeline. If the pipeline has almost 0% success rate in last 30 days then it has very little value.

**Comment by ruanxin** [comment]
Hi @Sawthis, thanks for the feedback. tbh, I don't share the same opinion here, we reported this issue on Nov 10, it take times for us to analysis and delegate to responsible team to fix this issue, during this duration, the pipeline will continue failing unfortunately, but that's not indicate the pipeline has no value, it tells us this problem is not fixed yet, and remind us to keep tracking on it, that's the value. If possible, a better solution could be stop this periodical job temporary until bug fixed, but not remove it.

**Comment by Sawthis** [comment]
Hi @ruanxin then please disable it next time if pipeline is failing due to known bug.

**Comment by janmedrek** [comment]
I will add the @kyma-project/jellyfish to the CODEOWNERs for this specific file, we will get a notification for the PR but then - it will most likely still be possible to override our review requirement for modifications to the pipeline. That does not solve the problem, but rather somehow helps us notice that in the future.

Also, @VladislavPaskar as the pipeline is quite important I would ask you to reintroduce it as soon as it's possible, I guess when the new Kyma version is out. You can also reintroduce it but disable it for now, and after the release is done enable it again (that would be the preferred solution). Please let me know what is your decision in this topic, I will bring it up again once the release is done.

**Comment by VladislavPaskar** [comment]
> @ruanxin @VladislavPaskar Yes, this pipeline tests from second latest released Kyma to latest release. Thus, if we bring it back now it will fail until next release, which is planed for 28th of December. Thus, it will fail for over two weeks and thus, be removed again by `neighbours`.
> 
> @Sawthis what do you think? Reintroduce them now, but it will fail until end of December. Or Tunas need to make sure to reintroduce it at same time as release is happening.
> 
> @VladislavPaskar one more question, since we currently have a breaking bug in eventing when a customer tries to upgrade its Kyma cluster. Don't you think we should release earlier, since every customer will encounter this situation when 2.9.2 goes live. @Sawthis you are managing the 2.9.x releases (afaik) - Would also be good to get your opinion here.
> 
> (cc @zhoujing2022)

I am not sure which bug do you mean. If you mean the one, which you encontered in the pipeline, then it more about the wrong sequence of the tests execution.

**Comment by VladislavPaskar** [comment]
> I will add the @kyma-project/jellyfish to the CODEOWNERs for this specific file, we will get a notification for the PR but then - it will most likely still be possible to override our review requirement for modifications to the pipeline. That does not solve the problem, but rather somehow helps us notice that in the future.
> 
> Also, @VladislavPaskar as the pipeline is quite important I would ask you to reintroduce it as soon as it's possible, I guess when the new Kyma version is out. You can also reintroduce it but disable it for now, and after the release is done enable it again (that would be the preferred solution). Please let me know what is your decision in this topic, I will bring it up again once the release is done.

@jeremyharisch @janmedrek as far as I understood, we need to bring back the pipeline and disable it for now or should it stay enabled, so that the jellyfish would keep their eyes on it ?

**Comment by jeremyharisch** [comment]
OK, if it is just a testing problem, then we do not have a blocking bug 👍🏻

**Comment by janmedrek** [comment]
@VladislavPaskar There is no point in having a pipeline that will run red, it will just burn up the infra money. I would just ask you to enable/reintroduce the pipeline when it has the potential to turn green, which (if I am correct) would be at some point the next release is out.

**Comment by VladislavPaskar** [comment]
> @VladislavPaskar There is no point in having a pipeline that will run red, it will just burn up the infra money. I would just ask you to enable/reintroduce the pipeline when it has the potential to turn green, which (if I am correct) would be at some point the next release is out.

I see, that make sense. We will re-enable it after the release.

**Comment by VladislavPaskar** [comment]
Here is the [PR](https://github.com/kyma-project/test-infra/pull/6410) to bring back this pipeline.

**Comment by marcobebway** [comment]
Moving to blocked because the [PR](https://github.com/kyma-project/kyma/pull/16278) is not merged to the release 2.9 branch, but since it is merged to main, it will be available with the upcoming Kyma release 2.10.X.

**Comment by adityabhatia** [comment]
@marcobebway even after releasing 2.10 the issue still persists, could you have a look?

**Comment by marcobebway** [comment]
@adityabhatia added to the next sprint.

**Comment by raypinto** [comment]
@adityabhatia From what I see in the logs, it looks like now all the tests pass but the final cleanup fails. The upgrade tests (as mentioned in the description) look good now.

**Comment by raypinto** [comment]
Closing this issue in favour of [this one](https://github.com/kyma-project/kyma/issues/16653)
