### ISSUE TITLE
Improve Backup

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#2994]
**Description**

Based on the first backup setup we identified missing topics. Some components are not covered in E2E tests, some tests are failing. 

Backup Documentation: https://kyma-project.io/docs/master/components/backup/
E2E Test and Integration Guide: https://github.com/kyma-project/kyma/tree/master/resources/ark
E2E Test: https://github.com/kyma-project/kyma/tree/master/tests/end-to-end/backup-restore-test/

AC:
- All components are backuped

**Reasons**

- Prevent data los during operations.

**Comment by piotrmsc** [comment]
@joek Would be nice to add execution of our all kyma tests (testing.sh) as a part of  the framework -- after executing all test scenarios. Thanks to that we would not have to duplicate ourselves with scenarios for creating resources after backup restore in order to verify if component is still working properly. What do you think?

**Comment by joek** [comment]
Ok, the plan is to run testing.sh after our current backup / restore test to make shure the cluster is still running as expected after the restore.

Makes sense. Let's see where we can squeeze it in.

**Comment by jakkab** [comment]
@joek @k15r I've encountered several obstacles while working on issues in this epic:
- e2e tests can be performed exclusively on Automatix's onDemand cluster. Neither prow e2e testing pipeline (target environment), nor GKE clusters support backup'n'restore (Ark not configured, missing resources);
- Ark configuration is not included in B'n'R docu;
- Existing tests for several components tend to fail, so running e2e tests requires disabling those failing tests in Go code (i.e. building new image. Final image built by post-submit Prow pipeline always fails).

**Comment by polskikiel** [comment]
I've encountered the trouble with creating the backup-restore test of helm broker.
The scenario looks as follows:
1. I provision a Redis service instance - underhood it's installing the helm chart(https://github.com/kyma-project/bundles/tree/master/bundles/redis-0.0.3/chart/redis).
- The information about the created instance is stored in the service catalog's etcd.
2. After backup is ready, I delete this service instance with its namespace.
- The information about the instance stored in etcd is being deleted.
3. After restoring we expect to have information about the instance again in the etcd. But it's not being restored.
- Without that information, the Helm broker tries to install the bundle's chart once again in the namespace and fails with the already exists error.

**Update:**
I've deleted the `helm-broker` and `service-catalog` releases in the test after doing backup and they wasn't restored.

**Comment by polskikiel** [comment]
I've encountered the trouble with creating the backup-restore test of helm broker.
The scenario looks as follows:
1. I provision a Redis service instance - underneath it's installing the helm chart(https://github.com/kyma-project/bundles/tree/master/bundles/redis-0.0.3/chart/redis).
- The information about the created instance is stored in the service catalog's etcd.
2. After backup is ready, I delete this service instance with its namespace.
- The information about the instance stored in etcd is being deleted.
3. After restoring we expect to have information about the instance again in the etcd. But it's not being restored.
- Without that information, the Helm broker tries to install the bundle's chart once again in the namespace and fails with the already exists error.

**Update:**
I've deleted the `helm-broker` and `service-catalog` releases in the test after doing backup and they weren't restored.

Does anybody know if I'm doing sth wrong?

**Comment by joek** [comment]
@jakkab 
> * e2e tests can be performed exclusively on Automatix's onDemand cluster. Neither prow e2e testing pipeline (target environment), nor GKE clusters support backup'n'restore (Ark not configured, missing resources);

It should run on all Azure onDemand Clusters. If not, please check what's going on there as we have not done any customisation to it.

> * Ark configuration is not included in B'n'R docu;

Please find the ark config documentation as part of the B'n'R docu for you:
- https://github.com/kyma-project/kyma/blob/master/docs/backup/docs/03-01-backup-configuration.md
- https://github.com/kyma-project/kyma/blob/master/docs/backup/docs/01-01-backup.md

By purpose we have not duplicated the entire ark documentation. If you think some highly required information is missing, we are happy to see your pull request. 

> * Existing tests for several components tend to fail, so running e2e tests requires disabling those failing tests in Go code (i.e. building new image. Final image built by post-submit Prow pipeline always fails).

The failing ones should be fixed by today. We will have an eye on the situation and get in touch with the people who make them fail to fix it.

**Comment by joek** [comment]
> I've encountered below issue with creating the backup-restore test of helm broker.
> The scenario looks as follows:
> 
> 1. I provision a Redis service instance - underneath it's installing the helm chart(https://github.com/kyma-project/bundles/tree/master/bundles/redis-0.0.3/chart/redis).
> 
> * The information about the created instance is stored in the service catalog's etcd in kyma-system.
> 
> 1. After backup is ready, I delete this service instance with its namespace.
> 
> * The information about the instance stored in etcd is being deleted.
> 
> 1. **After restoring we expect to have information about the instance again in the etcd of service catalog in kyma-system. But it's not being restored.**
> 
> * Without that information, the Helm broker tries to install the bundle's chart once again in the namespace and fails with the already exists error.
> 
> **Update:**
> I've deleted the `helm-broker` and `service-catalog` releases in the test after doing backup and they weren't restored.
> 
> Does anybody know if I'm doing sth wrong?

We are working on in and will get in touch with you via slack.

**Comment by polskikiel** [comment]
Hello, I collected some feedback about the test framework:
- Restore should be run on the clean cluster.
- In addition to periodic job, backup-restore test should be run by prow on image bump (separate pipeline). Now the developers will know that his image bump causes this test to fail on GKE only when the next execution of the periodic job will fail.
- Backup-restore test runs multiple tests in the loop and doesn't provide any logging which makes errors tracking very hard.
- Tests executions should be independent, if one test fails the others should still be executed. Now the tests are executed in the loop and if the first test fails the other ones are skipped and the test goes on.
-  All waiting methods using its own implementations. We should use common library for it or just to create a one function which will ensure a correct implementation for all of them.
- Provided test framework and test cases are nondeterministic. Test should be run multiple times before merge to provide stable timeouts.
- Test should be more generic – now it assumes that every time we will test resources after the restore in the same way as we did before the restore. 
- Configuration for backup should be in `test/end-to-end/backup-restore-tests` folder, not in `docs/backup/assets`. In the `docs/backup/assets` folder we should have only the example of the configuration with proper comments explaining the configuration options.
- Full documentation should be provided (what is being restored, which namespaces, resources and how to configure it) – that documentation exists in kyma docs but should be mentioned in the test’s readme.
- Test should pass on CI.

**Comment by k15r** [comment]
> I've encountered below issue with creating the backup-restore test of helm broker.
> The scenario looks as follows:
> 
> 1. I provision a Redis service instance - underneath it's installing the helm chart(https://github.com/kyma-project/bundles/tree/master/bundles/redis-0.0.3/chart/redis).
> 
> * The information about the created instance is stored in the service catalog's etcd in kyma-system.
> 
> 1. After backup is ready, I delete this service instance with its namespace.
> 
> * The information about the instance stored in etcd is being deleted.
> 
> 1. **After restoring we expect to have information about the instance again in the etcd of service catalog in kyma-system. But it's not being restored.**

The problem is that ark does not restore resources that still exist in the cluster. And you cannot force it to do so. If you want to revert to a previous state of the etcd then you need to wipe it.
> 
> * Without that information, the Helm broker tries to install the bundle's chart once again in the namespace and fails with the already exists error.
> 
> **Update:**
> I've deleted the `helm-broker` and `service-catalog` releases in the test after doing backup and they weren't restored.
> 
> Does anybody know if I'm doing sth wrong?

**Comment by polskikiel** [comment]
@k15r Thanks, but as I said before I've deleted the helm-broker release - it contains the etcd for helm-broker and it didn't restore properly. 
I tried to delete only the etcd stateful set before restore - the etcd data has also not been restored.
I've also tried to delete only the persistence volume, sadly with no effect.
